apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deploy
  labels:
    app: node-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-web-app
        image: saikishore789/nodeapp-login
        ports:
        - containerPort: 8080
