
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-rs
spec:
  replicas: 2
  selector:
     matchLabels:
       app: hello-world
  template:
     metadata:
       labels:
         app: hello-world
     spec:
       containers:
       - name: hello-ctr
         image: nigelpoulton/k8sbook:latest
         ports:
         - containerPort: 8080
